### ISSUE TITLE
本项目应当采用 GPL-3.0，而不是 BSD-3-Clause

### ISSUE THREAD

**Issue by kahaani** [Sillyplus/Dioghv#1]
你好。

[Kahaani/dieghv](https://github.com/Kahaani/dieghv) 是以 [GPL-3.0](https://github.com/Kahaani/dieghv/blob/master/LICENSE) 开源的。

本项目的 [/DboardKit/data/](https://github.com/Sillyplus/Dioghv/tree/master/DboardKit/data) 目录下的六种口音的字音数据是来自 [Kahaani/dieghv](https://github.com/Kahaani/dieghv) 的。

根据 GPL 的要求，本项目应当保留原项目的 LICENSE 和 COPYRIGHT 信息，并且以相同的方式也即 GPL-3.0 开源。

谢谢。

**Comment by Sillyplus** [comment]
你好，十分感谢你的反馈，我会在近日移除这部分数据，同时该项目也会直接废弃删除。
